include_guard(GLOBAL)
get_filename_component(DIMINA_WASM_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(dimina_configure_wasm target)
    if(NOT TARGET dimina_wamr)
        add_subdirectory("${DIMINA_WASM_ROOT}/third_party/wamr" "${CMAKE_BINARY_DIR}/dimina_wamr")
    endif()
    target_sources(${target} PRIVATE "${DIMINA_WASM_ROOT}/native/wasm/dimina_wasm.cpp")
    target_include_directories(${target} PRIVATE "${DIMINA_WASM_ROOT}/native/wasm/include")
    target_compile_features(${target} PRIVATE cxx_std_17)
    target_link_libraries(${target} PRIVATE dimina_wamr)
endfunction()
